CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(30),
    password_hash VARCHAR(255) NOT NULL,
    birth_date DATE,
    gender VARCHAR(20),
    main_specialty VARCHAR(100),
    secondary_specialties TEXT,
    order_number VARCHAR(100),
    experience_years INT,
    bio TEXT,
    cabinet_name VARCHAR(150),
    address TEXT,
    city VARCHAR(100),
    postal_code VARCHAR(20),
    cabinet_phone VARCHAR(30),
    establishment_type VARCHAR(100),
    cabinet_logo VARCHAR(255),
    ice VARCHAR(50),
    ifiscal VARCHAR(50),
    cnss VARCHAR(50),
    rib VARCHAR(50),
    language VARCHAR(20) DEFAULT 'fr',
    timezone VARCHAR(50) DEFAULT 'Africa/Casablanca',
    notifications_email BOOLEAN DEFAULT TRUE,
    notifications_sms BOOLEAN DEFAULT FALSE,
    notifications_whatsapp BOOLEAN DEFAULT FALSE,
    account_status VARCHAR(20) DEFAULT 'PENDING',
    is_email_verified BOOLEAN DEFAULT FALSE,
    enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
